services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"

  backend:
    env_file:
      - .env
    build:
      context: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    depends_on:
      - redis
      - rabbitmq
      - celery_worker
    command: flask run --host=0.0.0.0
    networks:
      - my_network

  redis:
    image: "redis:alpine"
    networks:
      - my_network
  
  rabbitmq:
    image: "rabbitmq:alpine"
    ports:
      - "15672:15672"  # Porta per interfaccia di gestione
      - "5672:5672"    # Porta per la connessione del broker
    networks:
      - my_network
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf


  # Worker Celery
  celery_worker:
    build:
      context: ./backend
    command: celery -A main.celery worker --loglevel=info -E
    volumes:
      - ./backend:/app
    depends_on:
      - redis
      - rabbitmq
    env_file:
      - .env
    user: "1000:1000"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge